on:
  push:
    branches: [main,master]
  pull_request:
    branches: [main]
jobs:
  test_job:
    name: test_actions
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
        
      - name: SetUp Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Maven Clean
        run: mvn clean
        
      - name: Maven Install
        run: mvn install
        
      - name: Maven Package
        run: mvn package

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pokeapi:latest
      
